# Generated by Django 4.1.2 on 2022-10-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
    ]
